### ISSUE TITLE
rez-pip fails due to Windows short file names

### ISSUE THREAD

**Issue by SuperValou** [JeanChristopheMorinPerso/rez-pip#49]
When using rez-pip to install a package on Windows, the installation fails.

**Environment**
* Windows 10.0
* rez-pip 0.2.0
* rez-pip being installed in its own virtual environment, not part of a rez installation

**To Reproduce**
- Rezify a python 3.7.7 interpreter through [this utility](https://github.com/techartorg/rez_utils/tree/main/rezify_python)
- Install rez-pip into its own virtualenv
- open a terminal
- run `cd C:\rez-pip\Scripts` then `.\activate` to enter the virtualenv of `rez-pip`
- run `.\rez-pip2 urllib3`
- see the error:
```
(rez-pip) PS C:\rez-pip\Scripts> rez-pip2 urllib3
INFO     Installing requested packages for Python 3.7.7
INFO     Resolved 1 dependencies for python 3.7.7
INFO     Downloading...
INFO     Downloaded urllib3-2.0.6 to
         'C:\\Users\\SUPERV~1\\AppData\\Local\\Temp\\rez-pip-targetod9cqugz\\wheels\\urllib3-2.0.6-py3-none-any.whl'
         (123799 bytes)
INFO     Downloaded 1 wheels
INFO     Installing urllib3-2.0.6 wheel
INFO     Creating rez package for urllib3
INFO     Installing urllib3-2.0.6 []
Traceback (most recent call last):
  File "c:\users\supervalou\packages\python\3.7.7\platform-windows\arch-AMD64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\supervalou\packages\python\3.7.7\platform-windows\arch-AMD64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\rez-pip\Scripts\rez-pip2.exe\__main__.py", line 9, in <module>
  File "c:\rez-pip\lib\site-packages\rez_pip\cli.py", line 318, in run
    _run(args, pipArgs, pipWorkArea)
  File "c:\rez-pip\lib\site-packages\rez_pip\cli.py", line 219, in _run
    release=args.release,
  File "c:\rez-pip\lib\site-packages\rez_pip\rez.py", line 127, in createPackage
    pkg.pip["metadata"] = remainingMetadata
  File "c:\users\supervalou\packages\python\3.7.7\platform-windows\arch-AMD64\lib\contextlib.py", line 119, in __exit__
    next(self.gen)
  File "c:\rez-pip\lib\site-packages\rez\package_maker.py", line 237, in make_package
    make_root(variant_, root)
  File "c:\rez-pip\lib\site-packages\rez_pip\rez.py", line 74, in make_root
    path, srcAbsolute.relative_to(os.path.realpath(installedWheelsDir))
  File "c:\users\supervalou\packages\python\3.7.7\platform-windows\arch-AMD64\lib\pathlib.py", line 895, in relative_to
    .format(str(self), str(formatted)))
ValueError: 'C:\\Users\\supervalou\\AppData\\Local\\Temp\\rez-pip-targetod9cqugz\\installed\\3.7.7\\python\\urllib3\\__init__.py' does not start with 'C:\\Users\\SUPERV~1\\AppData\\Local\\Temp\\rez-pip-targetod9cqugz\\installed\\3.7.7'
```

**Expected behavior**
Program installs urllib3 as a rez package.

**Actual behavior**
The error above occurs and nothing gets installed.

**Investigation**
This clearly seems to be due to a string comparison between a [windows short name](https://en.wikipedia.org/wiki/8.3_filename) (`C:/Users/SUPERV~1/...`) and its corresponding [long name](https://en.wikipedia.org/wiki/Long_filename)  (`C:/Users/supervalou/...`).

Adding some os.realpath around [this line](https://github.com/JeanChristopheMorinPerso/rez-pip/blob/3cc36bc1def563677247255d311116bbeae5b0c6/src/rez_pip/rez.py#L71) may fix this issue.

**Comment by SuperValou** [comment]
Replacing [this line](https://github.com/JeanChristopheMorinPerso/rez-pip/blob/3cc36bc1def563677247255d311116bbeae5b0c6/src/rez_pip/rez.py#L74):
```python
path, srcAbsolute.relative_to(os.path.realpath(installedWheelsDir))
```
 with 
```python
path, srcAbsolute.relative_to(pathlib.Path(installedWheelsDir).resolve())
```
fixes the issue on my side.

**Comment by JeanChristopheMorinPerso** [comment]
Thanks for the report! Do you want to submit a PR?
