### ISSUE TITLE
Fail to install boxsdk

### ISSUE THREAD

**Issue by brycegbrazen** [JeanChristopheMorinPerso/rez-pip#65]
When running a `rez-pip2` install on the `boxsdk` PyPi package, the install fails with a UnicodeDecodeError.

**Environment**
* Windows
* Rez version 2.112.0
* Rez python version 3.7
* rez-pip 0.3.0

**To Reproduce**
1. Install new rez-pip
2. ` rez-pip2 boxsdk==3.9.2 --python-version 3.7` (seems to fail with at least all 3.x.x versions)

**Expected behavior**
Successful install.

**Actual behavior**
```
INFO     Installing requested packages for Python 3.7.9
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Rez\Scripts\rez-pip2.exe\__main__.py", line 7, in <module>
  File "c:\program files\rez\lib\site-packages\rez_pip\cli.py", line 318, in run
    _run(args, pipArgs, pipWorkArea)
  File "c:\program files\rez\lib\site-packages\rez_pip\cli.py", line 183, in _run
    pipArgs,
  File "c:\program files\rez\lib\site-packages\rez_pip\pip.py", line 131, in getPackages
    rawData = json.load(fd)
  File "C:\Python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3565: character maps to <undefined>
```

**Comment by JeanChristopheMorinPerso** [comment]
I think this was recently fixed but the fix isn't released yet. Can you try to install rez-pip from the main branch and see if it fixes your problem?

```
pip install git+https://github.com/JeanChristopheMorinPerso/rez-pip.git
```

**Comment by brycegbrazen** [comment]
@JeanChristopheMorinPerso Yep the latest 0.4.0.dev1 fixes the issue thanks! Though trying an install including the "jwt" extra doesn't seem to work.
```
rez-pip2 boxsdk[jwt]==3.9.2 --python-version 3.7
```
Then following with a 
```
rez-env boxsdk
```
doesn't give me an environment with boxsdk and the extra "jwt" as a requirement.

```
(Rez) λ rez-env boxsdk

You are now in a rez-configured environment.


requested packages:
boxsdk
~platform==windows  (implicit)
~arch==AMD64        (implicit)
~os==windows-10     (implicit)

resolved packages:
arch-AMD64                c:\users\bryce.gattis\packages\arch\AMD64                                                         (local)
attrs-23.1.0              c:\users\bryce.gattis\packages\attrs\23.1.0\9339b6c5b8ac5a36d2fe05955f7aabccec716f73              (local)
boxsdk-3.9.2              c:\users\bryce.gattis\packages\boxsdk\3.9.2                                                       (local)
certifi-2023.7.22         c:\users\bryce.gattis\packages\certifi\2023.7.22                                                  (local)
charset_normalizer-3.3.2  c:\users\bryce.gattis\packages\charset_normalizer\3.3.2\69fe24dc50b5aaf01d2aab48736b310ab772af5a  (local)
idna-3.4                  c:\users\bryce.gattis\packages\idna\3.4                                                           (local)
importlib_metadata-6.7.0  c:\users\bryce.gattis\packages\importlib_metadata\6.7.0\2df28e0bc062e97a470ee8f031a0e032702c394c  (local)
platform-windows          c:\users\bryce.gattis\packages\platform\windows                                                   (local)
python-3.7.9              c:\users\bryce.gattis\packages\python\3.7.9\platform-windows\arch-AMD64                           (local)
python_dateutil-2.8.2     c:\users\bryce.gattis\packages\python_dateutil\2.8.2                                              (local)
requests-2.31.0           c:\users\bryce.gattis\packages\requests\2.31.0                                                    (local)
requests_toolbelt-1.0.0   c:\users\bryce.gattis\packages\requests_toolbelt\1.0.0                                            (local)
six-1.16.0                c:\users\bryce.gattis\packages\six\1.16.0                                                         (local)
typing_extensions-4.7.1   c:\users\bryce.gattis\packages\typing_extensions\4.7.1                                            (local)
urllib3-2.0.7             c:\users\bryce.gattis\packages\urllib3\2.0.7                                                      (local)
zipp-3.15.0               c:\users\bryce.gattis\packages\zipp\3.15.0                                                        (local)
```
I'm missing jwt and cryptography as noted [here](https://github.com/box/box-python-sdk/blob/v3.9.2/setup.py#L79).

**Comment by JeanChristopheMorinPerso** [comment]
Can you open a different issue? I'll close this one.

**Comment by JeanChristopheMorinPerso** [comment]
Fixed by https://github.com/JeanChristopheMorinPerso/rez-pip/pull/63
